spring:
  config:
    activate:
      on-profile: secret
  mail:
    host: smtp.naver.com
    port: 465
    username: 
    password: 
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://13.125.128.164:3306/test
    username: test01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host:
      port:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.20.0.2:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


JWT:
  secret-key: 
  expiration-time: 
  refresh-expiration-time: 
  header: 
  prefix: Bearer