spring:
  config:
    activate:
      on-profile: local
  mail:
    host: smtp.naver.com
    port: 465
    username: so6918@naver.com
    password: Sunnytoday1!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      connect-timeout: 2000
      password: ${REDIS_PASSWORD}
      port: 6379


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true

JWT:
  secret-key: wooyanofightingsecretjwtwooyanofightingsecretjwtbye
  expiration-time: 600000
  refresh-expiration-time: 86400000
  header: Authorization
  prefix: Bearer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**